services:
  bird-audio-pipeline:
    image: corvium-birdsong:latest
    volumes:
      - /etc/corvium/bird_audio_pipeline.conf:/etc/corvium/bird_audio_pipeline.conf:ro
      - /mnt/corvium-data/Intake:/data/Intake
      - /mnt/corvium-data/Intake_test:/data/Intake_test
      - /mnt/corvium-data/PersistentStorage:/data/PersistentStorage
      - /home/tom/Documents/logs/bird_audio_pipeline:/logs/bird_audio_pipeline
    networks:
      - Database-network

networks:
  Database-network:
    external: true